services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules  # ← これでコンテナ内のnode_modulesをホストと分離
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    command: npm run dev

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - backend